https://project-skyscanner.herokuapp.com/flights/

###

https://project-skyscanner.herokuapp.com/flights/1

###

POST https://project-skyscanner.herokuapp.com/flights/
Content-Type: application/json

{
  "id": 0,
  "aircraftId": 12,
  "sourceCity": "Volgograd",
  "destCity": "Moscow",
  "departureTime": 1607979600000,
  "arrivalTime": 200000,
  "journeyDuration": 500,
  "price": 15000
}

###

POST https://project-skyscanner.herokuapp.com/flights/
Content-Type: application/json

{
  "id": 1,
  "aircraftId": 12,
  "sourceCity": "TOKYO",
  "destCity": "MELBOURNE",
  "departureTime": 1607979600000,
  "arrivalTime": 200000,
  "journeyDuration": 160795000,
  "price": 150000
}

###

DELETE https://project-skyscanner.herokuapp.com/flights/6

###

GET https://project-skyscanner.herokuapp.com/flights/

###

GET  https://project-skyscanner.herokuapp.com/flights/search?sourceCity=ka&destCity=mo&departureTime=17.12.2020

###

GET https://project-skyscanner.herokuapp.com/flights/search?sourceCity=kaZAN&destCity=moSCOW&departureTime=17.12.2020

###

GET https://project-skyscanner.herokuapp.com/flights/by-aircraft/2

###

GET https://project-skyscanner.herokuapp.com/flights/search?sourceCity=ka&destCity=mo&departureTime=17.12.2020


###

GET http://project-skyscanner.herokuapp.com/flights/sort/price?sourceCity=ka&destCity=mo&departureTime=17.12.2020

###

GET http://project-skyscanner.herokuapp.com/flights/sort/departure?sourceCity=ka&destCity=mo&departureTime=17.12.2020

###

GET http://project-skyscanner.herokuapp.com/flights/sort/departure?sourceCity=osak&destCity=quebe&departureTime=20.12.2020

###

GET http://project-skyscanner.herokuapp.com/flights/search/return?sourceCity=kaz&destCity=mos&departureTime=17.12.2020&departureTimeBack=25.12.2020

###

GET  http://localhost:8080/flights/search/return?sourceCity=kaz&destCity=mos&departureTime=17.12.2020&departureTimeBack=25.12.2020

