http://localhost:8080/airCrafts

###

http://localhost:8080/flights/1

###
http://localhost:8080/flights/19

###

http://localhost:8080/flights/1/save?airline="Уральские Авиалинии"&model="Ил-62"&capacity=80
###


http://localhost:8080/flights/0/save?airline="British Airways"&model="Ил-95"&capacity=220

###

http://localhost:8080/flights/19/remove

###

http://localhost:8080/flights

###

http://localhost:8080/flights/

###

http://localhost:8080/flights/0/save?aircraftId=9&sourceCity=Kazakhstan&destCity=Turkey&departureTime=10000&arrivalTime=200000&journeyDuration=500&price=15000

###

http://localhost:8080/flights/8/delete
###

http://localhost:8080/flights/0/save?aircraftId=9&sourceCity=Kazakhstan&destCity=Turkey&departureTime=10000&arrivalTime=200000&journeyDuration=500&price=15000

###

http://localhost:8080/flights/0/save?aircraftId=12&sourceCity=Volgograd&destCity=Moscow&departureTime=10000&arrivalTime=200000&journeyDuration=500&price=15000

###

http://localhost:8080/flights/aircrafts/10

###

http://localhost:8080/flights/search?sourceCity=ka&destCity=tu&departureTime=10000

